---
driver:
  name: vagrant
  provision: true
  vagrantfiles: ['provision.rb']

provisioner:
  name: chef_zero

platforms:
  - name: debian-9

suites:
  - name: spine1
    driver:
      network:
        - ['private_network', { virtualbox__intnet: 'leaf1', ip: '10.0.0.1' }]
  - name: leaf1
    driver:
      network:
        - ['private_network', { virtualbox__intnet: 'leaf1', ip: '10.0.0.2' }]
